---
- name: install rkhunter
  yum: name=rkhunter state=present
  notify: rkhunter update

- name: template rkhunter.conf
  template: src=rkhunter.conf.j2 dest=/etc/rkhunter.conf mode=0640
  notify: rkhunter update

- name: deploy rkhunter sysconfig
  template: src=rkhunter.sysconfig.j2 dest=/etc/sysconfig/rkhunter mode=0640
