---
- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow
- name: Set ufw policy to deny all incoming traffic
  ufw: state=enabled direction=incoming policy=deny
- copy:
    dest=/etc/ssh/sshd_config
    src=sshd_config
  notify:
    - restart sshd
