---
- apt_key: url=https://packagecloud.io/gpg.key state=present
- apt_repository: repo="deb https://packagecloud.io/sr/vendor/ubuntu/ wily main" state=present
- apt: name=acts=1.2 state=present
- copy:
    dest=/etc/acts.conf
    src=acts.conf
    owner=root
    group=root
    mode=644
- copy:
    dest=/etc/cron.daily/acts
    content="#!/bin/sh\nacts\n"
    owner=root
    group=root
    mode=755
- file: path=/var/cache/tarsnap state=directory
- copy:
    dest=/usr/local/etc/tarsnap.conf
    src=tarsnap.conf
    owner=root
    group=root
    mode=644
