---
- apt_key: url=https://packagecloud.io/gpg.key state=present
- apt_repository: repo="deb https://packagecloud.io/sr/vendor/ubuntu/ wily main" state=present
- apt: name=acts=1.2 state=present
- copy:
    dest=/etc/acts.conf
    src=acts.conf
    owner=root
    group=root
    mode=644
- copy:
    dest=/etc/cron.daily/acts
    content="#!/bin/sh\nacts\n"
    owner=root
    group=root
    mode=755
- file: path=/var/cache/tarsnap state=directory
- copy:
    dest=/usr/local/etc/tarsnap.conf
    src=tarsnap.conf
    owner=root
    group=root
    mode=644
- apt: pkg={{ item }} state=present
  with_items:
    - ansible
    - curl
    - gcc
    - git
    - htop
    - jq
    - libgit2-dev
    - python-libcloud
    - pkg-config
    - screen
    - shellcheck
    - tig
    - tree
    - vim
    - vim-nox
- group: name=admin state=present
- user:
    state=present
    name={{dev_extra_user}}
    createhome=yes
    group=admin
    password=no
    shell=/bin/bash
- authorized_key:
    state=present
    user={{dev_extra_user}}
    key="{{ lookup('file', dev_extra_pubkey_path) }}"
- copy:
    dest=/etc/sudoers.d/10-admin-passwordless
    src=sudoers
    owner=root
    group=root
- user: name={{dev_extra_user}} groups=docker append=yes
