---
- apt: pkg={{ item }} state=present
  with_items:
    - gcc
    - git
    - htop
    - jq
    - libgit2-dev
    - python-libcloud
    - pkg-config
    - screen
    - shellcheck
    - tree
    - vim
    - vim-nox
- user:
    state=present
    name={{dev_extra_user}}
    createhome=yes
    group=sudo
    password=no
    shell=/bin/bash
- authorized_key:
    state=present
    user={{dev_extra_user}}
    key="{{ lookup('file', dev_extra_pubkey_path) }}"
    state=present
- user: name={{dev_extra_user}} groups=docker append=yes
