---
- apt: pkg={{ item }} state=present
  with_items:
    - ansible-doc
    - gcc
    - git
    - htop
    - jq
    - libgit2-dev
    - python-libcloud
    - pkg-config
    - screen
    - shellcheck
    - tree
- user: name=dev groups=docker append=yes
