---
- apt: pkg={{item}} state=present
  with_items:
    - ansible
    - apt-file
    - curl
    - gcc
    - git
    - gist
    - htop
    - irssi
    - jq
    - libgit2-dev
    - mercurial
    - pandoc
    - python-libcloud
    - pkg-config
    - ruby-github-markdown
    - screen
    - shellcheck
    - tig
    - tree
    - vim
    - vim-nox
- cronvar:
    state=present
    name="PATH"
    value="~/gobin:~/bin:/usr/local/go/bin:/usr/local/bin:/usr/bin:/bin"
    user="{{username}}"
- cron:
    state=present
    name="maildirpaper-sync"
    minute="*/20"
    user="{{username}}"
    job="/home/{{username}}/bin/maildirpaper-sync 2>&1 | logger -t maildirpaper -p cron.info"
