---
- apt: pkg={{ item }} state=present
  with_items:
    - ansible
    - apt-file
    - curl
    - gcc
    - git
    - htop
    - jq
    - libgit2-dev
    - python-libcloud
    - pkg-config
    - ruby-github-markdown
    - screen
    - shellcheck
    - tig
    - tree
    - vim
    - vim-nox
