---
- name: Download the Go tarball
  get_url: url={{ go_download_location }}
           dest=/usr/local/src/{{ go_tarball }}
           sha256sum={{ go_tarball_checksum }}

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- file: path=/usr/local/go state=absent
  when: go_version|failed or (not go_version|skipped and go_version.stdout != go_version_target)
- name: Extract the Go tarball if Go is not yet installed or if it is not the desired version
  unarchive: src=/usr/local/src/{{go_tarball}} dest=/usr/local
  when: go_version|failed or (not go_version|skipped and go_version.stdout != go_version_target)

- name: Setup PATH and GOPATH
  copy: src=golang.sh
        dest=/etc/profile.d
