---
sudo: required
dist: trusty
language: python
python: "2.7"
env:
- ANSIBLE_PLAYBOOK=playbooks/dev.yml
  ANSIBLE_INVENTORY=tests/inventory
  ANSIBLE_VAULT_PASSWORD_FILE=tests/vault-password
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl
install:
  - pip install ansible
script:
  - "bin/ansible-dev --syntax-check"
  - "bin/ansible-dev --connection=local --sudo"
