app:
  build: .
  privileged: true
  volumes:
    - ./:/app
  environment:
    ANSIBLE_PLAYBOOK: playbooks/dev.yml
    ANSIBLE_HOSTS: tests/inventory
    ANSIBLE_VAULT_FILE: tests/vault.yml
    ANSIBLE_VAULT_PASSWORD_FILE: tests/vault-password
