---
- hosts: all
  vars_files:
    - vars/defaults.yml
  roles:
    - { role: mivok0.sudo, sudo_users: ['root', '%admin'],
      sudo_nopassword: true }
    - { role: resmo.fail2ban }
    - { role: sfromm.rkhunter, rkhunter_mail: logwatch_mailto }
    - common
    - { role: tarsnap, tags: ['tarsnap'] }
    - { role: vdirsyncer, tags: ['vdirsyncer'] }
    - { role: cbk, tags: ['cbk'] }
