# Install latest Docker release from the official apt repository
---
- apt_key:
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"
- apt_repository:
    repo="deb https://apt.dockerproject.org/repo/ ubuntu-wily main"
- apt: name=docker-engine
- service: name=docker state=started
- user: name={{item}} groups=docker append=yes
  with_items: "{{docker_authorized_users}}"
