- name: restart ntp
  service: name=ntp state=restarted
- name: restart rsyslog
  service: name=rsyslog state=restarted
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
