---
- shell: cat /etc/timezone
  register: current_timezone
- copy:
    content="{{timezone}}"
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  when: not current_timezone|skipped and current_timezone != timezone
  notify:
    - update timezone
