- apt: pkg={{ item }} state=present
  with_items:
    - libxml2
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev
    - zlib1g
    - python
    - python-dev
    - python-virtualenv
- pip: name=vdirsyncer virtualenv={{vdirsyncer_dir}}
