---
- include: install.yml
- file: path=/var/cache/tarsnap state=directory owner=root group=root
- copy:
    dest=/usr/local/etc/tarsnap.conf
    src=tarsnap.conf
    owner=root
    group=root
    mode=644
