---
- apt_key: url=https://packagecloud.io/gpg.key state=present
- apt: name=apt-transport-https state=present
- apt_repository: repo="deb https://packagecloud.io/sr/packages/ubuntu/ wily main" state=present
- apt: name=tarsnap={{tarsnap_version}} update_cache=true
- file: path=/var/cache/tarsnap state=directory owner=root group=root
- copy:
    dest=/usr/local/etc/tarsnap.conf
    src=tarsnap.conf
    owner=root
    group=root
    mode=644
