---
- apt_key: url=https://packagecloud.io/gpg.key state=present
- apt_repository: repo="deb https://packagecloud.io/sr/packages/ubuntu/ wily main" state=present
- apt: name=acts={{acts_version}} state=present update_cache=yes cache_valid_time=3600
- template:
    dest=/etc/acts.conf
    src=acts.conf.j2
    owner=root
    group=root
    mode=0640
- copy:
    dest="/etc/cron.{{acts_cron_frequency}}/acts"
    content="#!/bin/sh\nacts\n"
    owner=root
    group=root
    mode=0640
