# Install packages required for building debian packages and working with
# packagecloud.io
---
- apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - cdbs
    - debhelper
    - devscripts
    - dpkg-dev
    - lintian
    - ruby
    - ruby-dev
    - software-properties-common
- gem: name={{ item }} user_install=no state=present
  with_items:
    - fpm
    - package_cloud
