# Configure development environment for working on Pachyderm and related tools
---
- apt_key:
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"
- apt_repository:
    repo="deb https://apt.dockerproject.org/repo/ ubuntu-vivid main"
- apt: name=docker-engine
- apt: name=golang-go
- apt: name=golang-go.tools
