---
- name: Check current timezone
  shell: cat /etc/timezone
  register: current_timezone
- name: Set timezone
  copy:
    content={{timezone}}
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes
  when: current_timezone.stdout != timezone
  notify:
    - update timezone
